### ISSUE TITLE
Buying Item using a disconnected player's troll doesn't consume gold

### ISSUE THREAD

**Issue by Jaccouille** [island-troll-tribes/island-troll-tribes#342]
Title should be explicit.

**Comment by jonathanmclaus** [comment]
I think that this occurs because when an item is bought, the gold of each member of the tribe is synced to that of the owner of the triggering unit. However, if you buy with another player's unit, then the owner of the unit of the gold is unaffected. If that is the issue, this could happen anytime you have `-sc` enabled, not just after a player leaves.

If the `EVENT_PLAYER_[SELL|PAWN|PICKUP]_ITEM` events allow for `GetTriggerPlayer`, than that should be used. If they do not, then the gold should be synced to the lowest amount on the team, not just that of the owner of the triggering unit. I think that technically you only have to modify this for the case you buy an item, as the other two always affect the owner of the triggering unit.
